platform :ios, '5.0'
pod 'AFNetworking',	'~> 1.2.1'
pod 'JSONKit',		'~> 1.4'
pod 'MTStatusBarOverlay', '~> 0.9.1'
pod 'RegexKitLite',	'~> 4.0'
pod 'CocoaLumberjack', 	'~> 1.6'
pod 'SSZipArchive',	'~> 0.2.3'
pod 'MBProgressHUD',	'~> 0.6'
pod 'SBJson',		'~> 3.2'
pod 'Godzippa',		'~> 0.1.2'
